apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cm.fullname" . }}
  labels:    
    {{- include "cm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: {{ .Values.strategy.type }}
  selector:
    matchLabels:
      app: {{ include "cm.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "cm.fullname" . }}
        {{- include "cm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: Sitecore_InstanceName
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: Database_Server
              valueFrom:
                secretKeyRef:
                  name: sitecore-database
                  key: Database_Server
            - name: Master_Database_Username
              valueFrom:
                configMapKeyRef:
                  name: global-config-env-file
                  key: Master_Database_Username
            - name: Master_Database_Password
              valueFrom:
                secretKeyRef:
                  name: sitecore-database
                  key: Master_Database_Password
            - name: Core_Database_Username
              valueFrom:
                configMapKeyRef:
                  name: global-config-env-file
                  key: Core_Database_Username
            - name: Core_Database_Password
              valueFrom:
                secretKeyRef:
                  name: sitecore-database
                  key: Core_Database_Password
            - name: Web_Database_Username
              valueFrom:
                configMapKeyRef:
                  name: global-config-env-file
                  key: Web_Database_Username
            - name: Web_Database_Password
              valueFrom:
                secretKeyRef:
                  name: sitecore-database
                  key: Web_Database_Password
            - name: Forms_Database_Username
              valueFrom:
                configMapKeyRef:
                  name: global-config-env-file
                  key: Forms_Database_Username
            - name: Forms_Database_Password
              valueFrom:
                secretKeyRef:
                  name: sitecore-database
                  key: Forms_Database_Password
            - name: Sitecore_ConnectionStrings_Sitecoreidentity.secret
              valueFrom:
                secretKeyRef:
                  name: sitecore-identity
                  key: Sitecore_ConnectionStrings_Sitecoreidentity_Secret
            - name: Sitecore_AppSettings_Telerik.AsyncUpload.ConfigurationEncryptionKey
              valueFrom:
                secretKeyRef:
                  name: sitecore-telerik
                  key: Sitecore_Telerik_Encryption_Key
            - name: Sitecore_AppSettings_Telerik.Upload.ConfigurationHashKey
              valueFrom:
                secretKeyRef:
                  name: sitecore-telerik
                  key: Sitecore_Telerik_Encryption_Key
            - name: Sitecore_AppSettings_Telerik.Web.UI.DialogParametersEncryptionKey
              valueFrom:
                secretKeyRef:
                  name: sitecore-telerik
                  key: Sitecore_Telerik_Encryption_Key
            - name: Sitecore_License
              valueFrom:
                secretKeyRef:
                  name: sitecore-license
                  key: Sitecore_License
            - name: Sql_Database_Prefix
              valueFrom:
                secretKeyRef:
                  name: sitecore-database
                  key: Sitecore_Database_Prefix  
            - name: LOG_LEVEL_VALUE
              valueFrom:
                secretKeyRef:
                  name: sitecore-common
                  key: Sitecore_Log_Level_Value
            - name: Sitecore_ConnectionStrings_Core
              value: Data Source=$(Database_Server);Initial Catalog=$(Sql_Database_Prefix).Core;User ID=$(Core_Database_Username);Password=$(Core_Database_Password);
            - name: Sitecore_ConnectionStrings_Security
              value: Data Source=$(Database_Server);Initial Catalog=$(Sql_Database_Prefix).Core;User ID=$(Core_Database_Username);Password=$(Core_Database_Password);
            - name: Sitecore_ConnectionStrings_Master
              value: Data Source=$(Database_Server);Initial Catalog=$(Sql_Database_Prefix).Master;User ID=$(Master_Database_Username);Password=$(Master_Database_Password);
            - name: Sitecore_ConnectionStrings_Web
              value: Data Source=$(Database_Server);Initial Catalog=$(Sql_Database_Prefix).Web;User ID=$(Web_Database_Username);Password=$(Web_Database_Password);
            - name: Sitecore_ConnectionStrings_ExperienceForms
              value: Data Source=$(Database_Server);Initial Catalog=$(Sql_Database_Prefix).ExperienceForms;User ID=$(Forms_Database_Username);Password=$(Forms_Database_Password);
            - name: Sitecore_ConnectionStrings_Solr.Search
              valueFrom:
                secretKeyRef:
                  name: sitecore-solr
                  key: Sitecore_ConnectionStrings_Solr
            - name: Sitecore_GraphQL_Enabled
              value: {{ .Values.graphQL.enabled | quote }}
            - name: Sitecore_GraphQL_ExposePlayground
              value: {{ .Values.graphQL.exposePlayground | quote }}
            - name: Sitecore_GraphQL_UploadMediaOptions_EncryptionKey
              valueFrom:
                secretKeyRef:
                  name: sitecore-security
                  key: SITECORE_GRAPHQL_UPLOADMEDIAOPTIONS_ENCRYPTIONKEY
            {{- with (first .Values.id.ingress.hosts) }}
            - name: Sitecore_Identity_Server_Authority
              value: {{ printf "https://%s" .host }}
            {{- end }}
            {{- with (first .Values.ingress.hosts) }}
            - name: Sitecore_Identity_Server_CallbackAuthority
              value: {{ printf "https://%s" .host }}
            {{- end }}
            - name: Sitecore_Identity_Server_InternalAuthority
              value: http://{{ .Values.id.serviceName }}
            - name: Sitecore_Identity_Server_Require_Https
              value: "false"
            - name: SOLR_CORE_PREFIX_NAME
              valueFrom:
                secretKeyRef:
                  name: sitecore-solr
                  key: Sitecore_Solr_Core_Prefix
            - name: SITECORE_JSS_EDITING_SECRET
              valueFrom:
                secretKeyRef:
                  name: sitecore-security
                  key: SITECORE_JSS_EDITING_SECRET            
            - name: MEDIA_REQUEST_PROTECTION_SHARED_SECRET
              valueFrom:
                secretKeyRef:
                  name: sitecore-security
                  key: MEDIA_REQUEST_PROTECTION_SHARED_SECRET
            - name: SITECORE_DEVELOPMENT_PATCHES
              valueFrom:
                configMapKeyRef:
                  name: global-config-env-file
                  key: SITECORE_DEVELOPMENT_PATCHES
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: 80
              httpHeaders:
              - name: X-Kubernetes-Probe
                value: Liveness
            timeoutSeconds: 300
            periodSeconds: 30
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /healthz/ready
              port: 80
              httpHeaders:
              - name: X-Kubernetes-Probe
                value: Startup
            timeoutSeconds: 300
            periodSeconds: 30
            failureThreshold: 10
          volumeMounts:
          - mountPath: C:\inetpub\wwwroot\App_Data\logs
            name: logs
            subPath: cm
          resources:
            {{- toYaml .Values.resources | nindent 12 }}  
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: logs
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}