apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rendering.fullname" . }}
  labels:    
    {{- include "rendering.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: {{ .Values.strategy.type }}
  selector:
    matchLabels:
      app: {{ include "rendering.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "rendering.fullname" . }}
        {{- include "rendering.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
          - name: SITECORE_API_HOST
            value: {{ printf "http://%s.%s.svc.cluster.local" .Values.global.cm.internalName .Release.Namespace }}
          {{- with (index .Values.global.rendering.ingress.tls 0) }}
          {{- with (index .hosts 0) }}
          - name: PUBLIC_URL
            value: {{ printf "https://%s" . }}
          {{- end }}
          {{- end }}
          - name: FETCH_WITH
            value: {{ .Values.settings.fetchMode }}
          - name: DEFAULT_LANGUAGE
            value: {{ .Values.settings.defaultLanguage }}
          - name: NEXTJS_DIST_DIR
            value: ".next"
          - name: PORT
            value: "80"
          - name: JSS_EDITING_SECRET
            valueFrom:
              secretKeyRef:
                name: sitecore-security
                key: SITECORE_JSS_EDITING_SECRET
          - name: SITECORE_API_KEY
            valueFrom:
              secretKeyRef:
                name: sitecore-security
                key: SITECORE_JSS_API_KEY
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}