apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: {{ .Values.keyvault.clientID }}
  labels:
    azure.workload.identity/use: "true"
  name: {{ .Values.serviceAccpuntName }}
  namespace: {{ .Values.envNamespace }}