replicaCount: 1

strategy:
  type: Recreate
image:
  repository: rendering
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: 
  - name: regcred-dev
nameOverride: ""
fullnameOverride: "sitecore-rendering"

metaLabels:
  business-owner: artsem.prashkovich
  technical-owner: artsem.prashkovich
  priority: medium

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: 
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-body-size: "512m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "256k"
  hosts:
    - host:
      paths:
        - path:
  tls:
  - secretName: local-tls
    hosts:

cd:
  serviceName:

cm:
  serviceName:

settings:
  fetchMode: GraphQL
  graphQlEndpoint: ""
  defaultLanguage: ""
  sitecoreApiHost: "cd"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    drop:
      - ALL
  allowPrivilegeEscalation: false
  runAsGroup: 3000
  readOnlyRootFilesystem: true
  runAsNonRoot: true
resources:
  requests:
    memory: 2500Mi
    cpu: 1000m
  limits:
    memory: 4Gi
    cpu: 1500m

nodeSelector:
  kubernetes.io/os: windows

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

tolerations: []
affinity: {}