sitecore-cd-role:
  image:
    repository: scr.sitecore.com/sxp/sitecore-xm1-cd
    tag: "10.3-ltsc2022"

sitecore-id-role:
  image:
    repository: scr.sitecore.com/sxp/sitecore-id7
    tag: "10.3-ltsc2022"

sitecore-rendering-role:
  enabled: true
  image:
    repository: ghcr.io/ampach/sitecore-sxastarter
    tag: "10.3-2"
  settings:
    fetchMode: GraphQL
    graphQlEndpoint: ""
    defaultLanguage: ""
    sitecoreApiHost: "cd"

sitecore-cm-role:
  image:
    repository: scr.sitecore.com/sxp/sitecore-xm1-cm
    tag: "10.3-ltsc2022"