replicaCount: 1

image:
  repository: rendering
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "10.2-ltsc2019"

imagePullSecrets: 
  - name: sitecore-docker-registry
nameOverride: ""
fullnameOverride: "sitecore-rendering"


service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts: []
  tls: []

settings:
  fetchMode: GraphQL
  graphQlEndpoint: ""
  defaultLanguage: ""
  sitecoreApiHost: "cd"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    drop:
      - ALL
  allowPrivilegeEscalation: false
  runAsGroup: 3000
  readOnlyRootFilesystem: true
  runAsNonRoot: true
resources:
  requests:
    memory: 2500Mi
    cpu: 1000m
  limits:
    memory: 4Gi
    cpu: 1500m

nodeSelector:
  kubernetes.io/os: windows

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

tolerations: []
affinity: {}