apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-ca-cert
  namespace: {{ .Values.envNamespace }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
spec:
  isCA: true
  commonName: local-ca-cert
  subject:
    organizations:
      - ACME Inc.
    organizationalUnits:
      - Widgets
  secretName: local-ca-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: self-signed-issuer
    kind: Issuer
    group: cert-manager.io