apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: local-ca-issuer
  namespace: {{ .Values.envNamespace }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "3"
spec:
  ca:
    secretName: local-ca-cert