apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-cert
  namespace: {{ .Values.envNamespace }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "4"
spec:
  secretName: tls-secret
  isCA: false
  commonName: "*.devops.family"
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - "*.devops.family"
  dnsNames:
  - "*.devops.family"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: Always
